version: '3.1'
services:
 db:
   image: postgres:13
   container_name: db_penjat
   environment:
     - POSTGRES_DB=penjat
     - POSTGRES_PASSWORD=pass
     - POSTGRES_USER=user
   ports:
     - "5433:5432"
   volumes:
     - local_pgdata:/var/lib/postgresql/data
 pgadmin:
   image: dpage/pgadmin4
   container_name: pg_penjat
   ports:
     - "8080:80"
   environment:
     PGADMIN_DEFAULT_EMAIL: roger@xtec.com
     PGADMIN_DEFAULT_PASSWORD: roger123
   volumes:
     - pgadmin-data:/var/lib/pgadmin
volumes:
 local_pgdata:
 pgadmin-data:
